// <auto-generated />
namespace NameLess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlteraçãodecampodeLocalização : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlteraçãodecampodeLocalização));
        
        string IMigrationMetadata.Id
        {
            get { return "201608102335493_Alteração de campo de Localização"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
